# =================================================================
# FILE: docker-compose.yml (FINAL-LATEST)
# DESCRIPTION: This version uses the :latest tag to ensure the
# newest version of n8n is always pulled after a cache clean.
# =================================================================
version: "3.8"

services:
  # 1. ORACYN Backend Service
  oracyn_backend_express:
    build: .
    container_name: oracyn_backend_express
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - N8N_WEBHOOK_URL=http://oracyn_n8n_service:5678/webhook/rag-workflow
      - N8N_WEBHOOK_URL_DOCUMENT=http://oracyn_n8n_service:5678/webhook/document-processing
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - INTERNAL_API_KEY=${INTERNAL_API_KEY}
    depends_on:
      - oracyn_postgres_db
      - oracyn_n8n_service
    volumes:
      - ./uploads:/usr/src/app/uploads
    networks:
      - oracyn-network

  # 2. PostgreSQL Database Service
  oracyn_postgres_db:
    image: postgres:15
    container_name: oracyn_postgres_db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ragdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - oracyn-network

  # 3. n8n Workflow Service
  oracyn_n8n_service:
    # THIS IS THE CORRECTED LINE:
    image: n8nio/n8n:latest
    container_name: oracyn_n8n_service
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=oracyn_n8n_service
      - N8N_PORT=5678
      - WEBHOOK_TUNNEL_URL=http://oracyn_n8n_service:5678/
      - INTERNAL_API_KEY=${INTERNAL_API_KEY}
    volumes:
      - n8n_data:/home/node/.n8n
      - ./uploads:/app/uploads
    networks:
      - oracyn-network

  # 4. Chroma DB Vector Store Service
  oracyn_chroma_db:
    image: chromadb/chroma
    container_name: oracyn_chroma_db
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma
    networks:
      - oracyn-network

volumes:
  postgres_data:
  n8n_data:
  chroma_data:

networks:
  oracyn-network:
    driver: bridge
